# Generated by Django 3.2 on 2023-02-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=70)),
                ('course_description', models.TextField()),
                ('course_publicated', models.DateTimeField(verbose_name='Date of Publication')),
            ],
        ),
    ]
