# Generated by Django 3.2 on 2023-02-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_publicated',
            new_name='date',
        ),
    ]
