# Generated by Django 3.2 on 2023-02-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0002_rename_course_publicated_course_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date',
            new_name='course_date',
        ),
    ]
